### ISSUE TITLE
Логика в клиенте

### ISSUE THREAD

**Issue by DjamikTea** [DjamikTea/hse_dsa#30]
Тимлид say:

1. Объединить генерацию ключа с регистрацией. Смысла регистрации нету если нет ключа.
2. Почему токен и сертификат не сохраняется при регистрации?
3. Сделать глобальный файл json куда будет сохраняться фио, телефон, pubkey, privkey или уже sqlite как я говорил.
4. Начинка файла не прилетает (пофиксил сам в клиенте)

Примечания:
- Говнокод
- Много повторяющегося кода
- Отсутствие структуры
- Ключи которые ты сохраняешь это не PEM формат

**Comment by DjamikTea** [comment]
### ТАКЖЕ НЕ МЕРЖИТ НЕ ГОТОВЫЙ КОД В MAIN!

**Comment by Morzan6** [comment]
Времени нет мержить готовый код
